#+title: Smona's Home Configuration

* Installation
*WARNING:* The install script will delete your existing dotfiles if they would
conflict with the installation process. Make sure to backup those dotfiles
before installing.

1. Clone this repository into ~$HOME/.config~.
2. ~cp settings.template.nix settings.nix~
3. Update ~settings.nix~ to reflect the machine you're installing on.
4. ~./install.sh~.

Have fun!

** Recommended manual steps
*** Set up syncthing shared folders
home-manager will install syncthing and enable its systemd service on machines
that use it.

Ensure syncthing is started, then go to [[http://localhost:8384][http://localhost:8384]] to add a GUI
password, link it to remote devices, and set up shared folders (such as ~/org in
my case). Who needs dropbox?

* Local Configuration
Several tools are set up to include local configuration files, to allow
overriding the reproducible configuration with arbitrary machine-specific
options.

- ~$HOME/.zsh.local~
- ~$HOME/.gitconfig.local~

I may one day decide to do this in a nix-ey way, but this is how my old
configuration worked, and it's a good setup.

* Backlog
** TODO note about previous repo for finding git history
** TODO refresh doom env on startup or disable
It leads to time wasted debugging problems caused by the environment not being
up to date when rapidly iterating on nix stuff.
