# Baremetal installation
{ inputs, self, ... }:
{
  flake.nixosConfigurations.luma = inputs.nixpkgs.lib.nixosSystem {
    pkgs = self.legacyPackages.x86_64-linux;
    specialArgs = {
      inherit inputs;
    };
    modules = [
      self.nixosModules.luma
      # Include the results of the hardware scan.
      self.nixosModules.luma-hardware
      self.nixosModules.llm-server
      self.nixosModules.pc
      ../../nixos/dualboot.nix
      self.nixosModules.amdgpu
      self.nixosModules.amd-cpu
      self.nixosModules.music
    ];
  };

  flake.nixosModules.luma =
    {
      config,
      pkgs,
      ...
    }:
    {
      smona.username = "mel";
      smona.primaryMonitor = "DP-1";
      smona.wallpaper = ../../wallpapers/vibrant-paint-streaks.jpg;
      networking.hostName = "luma"; # Define your hostname.

      home-manager.users.mel =
        { pkgs, ... }:
        {
          imports = [ ../../home.nix ];

          home.username = "mel";
          smona.wlroots.enable = true;
          smona.wlroots.primaryMonitor = config.smona.primaryMonitor;
          # gnome.enable = true;
          roles = {
            gaming = true;
            music = true;
          };
          logitech.enabled = true;
          # Should apply to any NixOS machine
          _1passwordBinary = "${pkgs._1password-gui}/bin/1password";
        };

      # List services that you want to enable:

      services.hardware.openrgb = {
        enable = true;
        package = pkgs.openrgb-with-all-plugins;
      };
      programs.coolercontrol.enable = true;
      environment.systemPackages = with pkgs; [
        liquidctl
      ];

      # This value determines the NixOS release from which the default
      # settings for stateful data, like file locations and database versions
      # on your system were taken. It‘s perfectly fine and recommended to leave
      # this value at the release version of the first install of this system.
      # Before changing this value read the documentation for this option
      # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
      system.stateVersion = "22.05"; # Did you read the comment?
    };

  # generated by ‘nixos-generate-config’.
  flake.nixosModules.luma-hardware =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "thunderbolt"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/43a491e1-470e-4145-bc09-b5a385ccc02e";
        fsType = "ext4";
      };

      fileSystems."/boot/efi" = {
        device = "/dev/disk/by-uuid/9A3E-7304";
        fsType = "vfat";
      };

      swapDevices = [
        { device = "/dev/disk/by-uuid/a84ce164-e31d-4ce0-8c5f-a0d87d9d79c0"; }
      ];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp11s0f2u1u3u4.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
      # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
