{ inputs, self, ... }:
{
  flake.nixosConfigurations.xps-nixos = inputs.nixpkgs.lib.nixosSystem {
    pkgs = self.legacyPackages.x86_64-linux;
    specialArgs = {
      inherit inputs;
    };
    modules = [
      # Include the results of the hardware scan.
      self.nixosModules.xps-nixos-hardware
      inputs.hardware.nixosModules.dell-xps-13-7390
      self.nixosModules.xps-nixos
      self.nixosModules.pc
      self.nixosModules.gaming
      self.nixosModules.realtime-audio
    ];
  };

  flake.nixosModules.xps-nixos =
    {
      config,
      pkgs,
      ...
    }:
    {
      smona.username = "smona";
      smona.primaryMonitor = "eDP-1";
      smona.wallpaper = ../../wallpapers/neon-highway-wallpaper.jpg;
      networking.hostName = "xps-nixos"; # Define your hostname.

      # Enable touchpad support (enabled default in most desktopManager).
      # services.xserver.libinput.enable = true;

      home-manager.users.smona =
        { pkgs, ... }:
        {
          imports = [ self.homeModules.linux-pc ];

          home.username = "smona";
          smona.wlroots = {
            enable = true;
            builtInDisplay = "eDP-1";
            primaryMonitor = config.smona.primaryMonitor;
          };
          roles = {
            art = true;
            gaming = true;
            music = true;
          };
          # Should apply to any NixOS machine
          _1passwordBinary = "${pkgs._1password-gui}/bin/1password";
        };

      virtualisation.virtualbox.host.enable = true;
      users.extraGroups.vboxusers.members = [ "smona" ];
      virtualisation.docker.enable = true;

      # Laptop stuff
      services.power-profiles-daemon.enable = false;
      services.tlp = {
        enable = true;
        settings = {
          CPU_SCALING_GOVERNOR_ON_AC = "performance";
          CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
          CPU_ENERGY_PERF_POLICY_ON_AC = "balance_performance";
          CPU_ENERGY_PERF_POLICY_ON_BAT = "balance_power";
        };
      };

      # Enable IIO for autorotation and light detection
      hardware.sensor.iio.enable = true;

      systemd.sleep.settings.Sleep = {
        HibernateDelaySec = "4h";
        # https://github.com/NixOS/nixos-hardware/tree/master/dell/xps/13-7390
        SuspendState = "freeze";
      };
      services.logind = {
        lidSwitch = "suspend-then-hibernate";
        lidSwitchExternalPower = "suspend-then-hibernate";
        settings.Login = {
          HandlePowerKey = "suspend-then-hibernate";
        };
      };

      # Open ports in the firewall.
      # networking.firewall.allowedTCPPorts = [ ... ];
      # networking.firewall.allowedUDPPorts = [ ... ];
      # Or disable the firewall altogether.
      # networking.firewall.enable = false;

      # This value determines the NixOS release from which the default
      # settings for stateful data, like file locations and database versions
      # on your system were taken. It‘s perfectly fine and recommended to leave
      # this value at the release version of the first install of this system.
      # Before changing this value read the documentation for this option
      # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
      system.stateVersion = "22.05"; # Did you read the comment?
    };

  # generated by ‘nixos-generate-config’.
  flake.nixosModules.xps-nixos-hardware =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:

    {
      imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "nvme"
        "usb_storage"
        "usbhid"
        "sd_mod"
        "rtsx_pci_sdmmc"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/5f3b3b70-4c05-471e-be08-03390534c06a";
        fsType = "ext4";
      };

      fileSystems."/boot/efi" = {
        device = "/dev/disk/by-uuid/F09E-A213";
        fsType = "vfat";
      };

      swapDevices = [ { label = "swap"; } ];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp3s0u1u3u4.useDHCP = lib.mkDefault true;
      # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

      # Set your system kind (needed for flakes)
      nixpkgs.hostPlatform = "x86_64-linux";
    };
}
